export const ROLES = {
  SYSTEM_ADMIN: "SYSTEM_ADMIN",
  COMPANY_ADMIN: "COMPANY_ADMIN",
  HR_ADMIN: "HR_ADMIN",
  HR: "HR",
  MANAGER: "MANAGER",
  EMPLOYEE: "EMPLOYEE",
  // Alias created by the self-registration flow (register-actions.ts).
  ADMIN: "ADMIN",
} as const;

export type RoleCode = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  // Company & Tenants
  COMPANY_MANAGE: "company:manage",
  COMPANY_VIEW: "company:view",
  COMPANY_UPDATE: "company:update",

  // Users & RBAC
  USER_MANAGE: "user:manage",
  ROLE_MANAGE: "role:manage",

  // Organization Structure
  ORGANIZATION_MANAGE: "organization:manage",
  BRANCH_MANAGE: "branch:manage",
  DEPARTMENT_MANAGE: "department:manage",
  POSITION_MANAGE: "position:manage",

  // Employees
  EMPLOYEE_READ: "employee:read",
  EMPLOYEE_CREATE: "employee:create",
  EMPLOYEE_UPDATE: "employee:update",
  EMPLOYEE_DELETE: "employee:delete",
  EMPLOYEE_IMPORT: "employee:import",
  EMPLOYEE_EXPORT: "employee:export",

  // Leave & Workflows
  LEAVE_READ: "leave:read",
  LEAVE_CREATE: "leave:create",
  LEAVE_APPROVE: "leave:approve",
  LEAVE_REJECT: "leave:reject",
  LEAVE_CANCEL: "leave:cancel",
  LEAVE_ADJUST: "leave:adjust",
  POLICY_MANAGE: "policy:manage",
  WORKFLOW_MANAGE: "workflow:manage",
  HOLIDAY_MANAGE: "holiday:manage",

  // LINE & Notifications
  LINE_MANAGE: "line:manage",
  ANNOUNCEMENT_MANAGE: "announcement:manage",

  // Reports & Audits
  REPORT_READ: "report:read",
  REPORT_EXPORT: "report:export",
  AUDIT_READ: "audit:read",

  // System Admin Scope
  SECURITY_MANAGE: "security:manage",
  SESSION_MANAGE: "session:manage",
  SYSTEM_SETTINGS: "system:settings",
  SYSTEM_HEALTH: "system:health",
  SYSTEM_LOGS: "system:logs",
  SYSTEM_BACKUP: "system:backup",
  SYSTEM_APIKEY: "system:apikey",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Static Role-to-Permissions fallback matrix.
 * Used for fast in-memory authorization checks and fallback resolution.
 */
export const ROLE_PERMISSIONS_MATRIX: Record<RoleCode, PermissionCode[]> = {
  [ROLES.SYSTEM_ADMIN]: [
    PERMISSIONS.COMPANY_MANAGE,
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_IMPORT,
    PERMISSIONS.EMPLOYEE_EXPORT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.LEAVE_ADJUST,
    PERMISSIONS.POLICY_MANAGE,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.HOLIDAY_MANAGE,
    PERMISSIONS.LINE_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SECURITY_MANAGE,
    PERMISSIONS.SESSION_MANAGE,
    PERMISSIONS.SYSTEM_SETTINGS,
    PERMISSIONS.SYSTEM_HEALTH,
    PERMISSIONS.SYSTEM_LOGS,
    PERMISSIONS.SYSTEM_BACKUP,
    PERMISSIONS.SYSTEM_APIKEY,
  ],
  [ROLES.COMPANY_ADMIN]: [
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_IMPORT,
    PERMISSIONS.EMPLOYEE_EXPORT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.LEAVE_ADJUST,
    PERMISSIONS.POLICY_MANAGE,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.HOLIDAY_MANAGE,
    PERMISSIONS.LINE_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.HR_ADMIN]: [
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_IMPORT,
    PERMISSIONS.EMPLOYEE_EXPORT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.LEAVE_ADJUST,
    PERMISSIONS.POLICY_MANAGE,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.HOLIDAY_MANAGE,
    PERMISSIONS.LINE_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.HR]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.POLICY_MANAGE,
    PERMISSIONS.HOLIDAY_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.AUDIT_READ,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.REPORT_READ,
  ],
  [ROLES.EMPLOYEE]: [
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_CANCEL,
  ],
  // Self-registered company admin (role code "ADMIN").
  // Grants the same permissions as COMPANY_ADMIN.
  [ROLES.ADMIN]: [
    PERMISSIONS.COMPANY_VIEW,
    PERMISSIONS.COMPANY_UPDATE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.BRANCH_MANAGE,
    PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.POSITION_MANAGE,
    PERMISSIONS.EMPLOYEE_READ,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_UPDATE,
    PERMISSIONS.EMPLOYEE_DELETE,
    PERMISSIONS.EMPLOYEE_IMPORT,
    PERMISSIONS.EMPLOYEE_EXPORT,
    PERMISSIONS.LEAVE_READ,
    PERMISSIONS.LEAVE_CREATE,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.LEAVE_REJECT,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.LEAVE_ADJUST,
    PERMISSIONS.POLICY_MANAGE,
    PERMISSIONS.WORKFLOW_MANAGE,
    PERMISSIONS.HOLIDAY_MANAGE,
    PERMISSIONS.LINE_MANAGE,
    PERMISSIONS.ANNOUNCEMENT_MANAGE,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.AUDIT_READ,
  ],
};

/**
 * Checks if a given role code has a specific permission.
 */
export function hasPermission(
  role: string | null | undefined,
  permission: string,
): boolean {
  if (!role) return false;

  const validRole = role as RoleCode;
  const permissions = ROLE_PERMISSIONS_MATRIX[validRole];

  if (!permissions) return false;
  return permissions.includes(permission as PermissionCode);
}

/**
 * Retrieves all permissions granted to a role.
 */
export function getRolePermissions(role: string): string[] {
  const validRole = role as RoleCode;
  return ROLE_PERMISSIONS_MATRIX[validRole] ?? [];
}
